const REQUEST_DOCUMENTS = 'REQUEST_DOCUMENTS';
const RECEIVE_DOCUMENTS = 'RECEIVE_DOCUMENTS';
const FETCH_DOCUMENTS_FAILURE = 'FETCH_DOCUMENTS_FAILURE';

const REQUEST_CATEGORIES="REQUEST_CATEGORIES";
const RECEIVE_CATEGORIES="RECEIVE_CATEGORIES";
const FETCH_CATEGORIES_FAILURE="FETCH_CATEGORIES_FAILURE";

const POST_DOCUMENT="POST_DOCUMENT";
const POST_DOCUMENT_SUCCESS="POST_DOCUMENT_SUCCESS";
const POST_DOCUMENT_FAILURE="POST_DOCUMENT_FAILURE";
const UPDATE_FIELD_DOCUMENT="UPDATE_FIELD_DOCUMENT";
const UPDATE_FILE_DOCUMENT="UPDATE_FILE_DOCUMENT";

export default {
    REQUEST_DOCUMENTS,
    RECEIVE_DOCUMENTS,
    FETCH_DOCUMENTS_FAILURE,
		REQUEST_CATEGORIES,
		RECEIVE_CATEGORIES,
		FETCH_CATEGORIES_FAILURE,
		POST_DOCUMENT,
		POST_DOCUMENT_SUCCESS,
		POST_DOCUMENT_FAILURE,
    UPDATE_FIELD_DOCUMENT,
    UPDATE_FILE_DOCUMENT
}